Import('env', 'suffix')
gen = env.Program('gen'+suffix, ['src/gen.cpp', 'src/sets.cpp'])
env.Program('jsm', ['src/jsm.cpp', 'src/sets.cpp'])
env.Program('jsm_classify', ['src/jsm_classify.cpp', 'src/sets.cpp'])
Default(gen)